[[redirects]]
  from = "/dictionary/*"
  to = "/bible/:splat"
  status = 301

[[redirects]]
  from   = "/ssl-2-plus-review/"
  to     = "/articles/ssl-2-plus-review.html"
  status = 301
  force  = false

[[redirects]]
  from   = "/ssl-2-plus-review"
  to     = "/articles/ssl-2-plus-review.html"
  status = 301
  force  = false
